before_all do
  ensure_git_branch
  ensure_git_status_clean
  git_pull
end

# $ fastlane android internal
platform :android do
  lane :internal do
    increment_version_code(gradle_file_path: './android/app/build.gradle')

    gradle(task: 'clean', project_dir: './android/')
    gradle(task: 'bundle', build_type: 'Debug', project_dir: './android/')
  
    # supply(track: 'internal', aab: './android/app/build/outputs/bundle/debug/app-debug.aab')
  end
end