# $ fastlane android internal
platform :android do
  desc "Deploy an internal test version to Google Play"

  lane :internal do
    increment_version_code(
      app_folder_name: './android/app',
      gradle_file_path: './android/app/build.gradle'
    )

    gradle(
      task: "clean", 
      project_dir: './android'
    )
    gradle(
      task: 'bundle',
      build_type: 'Release',
      project_dir: './android'
    )

    upload_to_play_store(
      track: 'internal', 
      release_status: 'draft', 
      json_key: './mindfulness_play_store_service_account.json'
    )
  end
end